apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: assessment-service
  description: Assessment service
  annotations:
    github.com/project-slug: my-org/assessment-service
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: production
  owner: Team-Transformation
  providesApis:
    - user-service-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: assessment-service-api
  description: API for assessment service

spec:
  type: openapi
  lifecycle: production
  owner: Team-Transformation
  definition:
    $text: ./api/openapi.yaml