apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: assessment-service
  description: Assessment service responsible for performing code assessments and generating modernization reports
  annotations:
    github.com/project-slug: Shubham2579/Backstage-Test
    backstage.io/techdocs-ref: dir:.
    github.com/workflows-ref: .github/workflows
    cicd.backstage.io/system: github-actions

spec:
  type: service
  lifecycle: production
  owner: group:default/team-transformation
  system: unisys

  providesApis:
    - assessment-service-api

  dependsOn:
    - component:default/genai-service
    - component:default/template-config

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: assessment-service-api
  description: REST API exposed by the Assessment Service

spec:
  type: openapi
  lifecycle: production
  owner: group:default/team-transformation
  system: unisys
  definition:
    $text: ./api/openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: genai-service
  description: AI service responsible for analyzing code and generating migration insights
  annotations:
    github.com/project-slug: Shubham2579/Backstage-Test
    github.com/workflows-ref: .github/workflows
    cicd.backstage.io/system: github-actions

spec:
  type: service
  lifecycle: production
  owner: group:default/team-transformation
  system: unisys

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: template-config
  description: Template configuration service used to generate reports and migration outputs
  annotations:
    github.com/project-slug: Shubham2579/Backstage-Test
    github.com/workflows-ref: .github/workflows
    cicd.backstage.io/system: github-actions

spec:
  type: service
  lifecycle: production
  owner: group:default/team-transformation
  system: unisys

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eclipse-plugin
  description: Eclipse IDE plugin used by developers to run modernization assessments
  annotations:
    github.com/project-slug: Shubham2579/Backstage-Test
    github.com/workflows-ref: .github/workflows
    cicd.backstage.io/system: github-actions

spec:
  type: application
  lifecycle: production
  owner: group:default/team-transformation
  system: unisys

  dependsOn:
    - component:default/assessment-service
    - component:default/genai-service
    - component:default/template-config
