apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: assessment-service
  description: Assessment service responsible for handling assessments
  annotations:
    # 1. This enables the "Source" on "GitHub"
    github.com/project-slug: CodeConnecter/Backstage-Test
    # 2. This enables the Azure Pipelines tab
    dev.azure.com/project-repo-build: 'YourAzureOrg/YourProjectName/YourPipelineName'
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: production
  owner: group:default/team-transformation
  system: examples

  providesApis:
    - assessment-service-api

  dependsOn:
    - component:default/user-service

  consumesApis:
    - api:default/auth-service-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: assessment-service-api
  description: API exposed by the assessment service

spec:
  type: openapi
  lifecycle: production
  owner: group:default/team-transformation
  system: examples
  definition:
    $text: ./api/openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: User management service

spec:
  type: service
  lifecycle: production
  owner: group:default/team-transformation
  system: examples

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service-api
  description: Authentication service API

spec:
  type: service
  lifecycle: production
  owner: group:default/team-transformation
  system: examples